### ISSUE TITLE
How to enable simple client traces ?

### ISSUE THREAD

**Issue by adustm** [ARMmbed/simple-mbed-cloud-client#15]
Hello,
I don't see the effect in the hyperterminal while writing
` "mbed-trace.enable": true` in mbed_app.json
I don't see the difference between trace = 0 and trace = true

I would like to be able to read the traces for this files, for instance https://github.com/ARMmbed/mbed-cloud-client/blob/9b0bc6a2f3f1f5dbb5be1827db83004d531b99c9/source/MbedCloudClient.cpp#L92

I am writing the following in mbed_app.json for the example cloud client
(based on https://github.com/ARMmbed/simple-mbed-cloud-client-template-restricted )
    "target_overrides": {
        "*": {
            "platform.stdio-baud-rate": 115200,
            "platform.stdio-convert-newlines": true,
            "update-client.storage-address"  : "(1024*1024*64)",
            "update-client.storage-size"     : "(1024*1024*2)",
            "update-client.storage-locations": "1",
            **"mbed-trace.enable": true**
        },

Platform: DISCO_F413ZH
toolchain GCC_ARM
gcc version 6 2017-q2-update

Could you advise me or fix that, please ?

**Comment by bridadan** [comment]
Turns out the initialization code for mbed_trace isn't included in the template app, I added it here: https://github.com/ARMmbed/simple-mbed-cloud-client-template-restricted/pull/23

**Comment by adustm** [comment]
Thank you so much Brian, the issue is fixed with this modification
Kind regards
Armelle

**Comment by MarceloSalazar** [comment]
Code merged. Expect to release this in the upcoming version of SMCC library.
