### ISSUE TITLE
Format not working on QSPI devices

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/simple-mbed-cloud-client#16]
## Problem
When using devices with QSPI instead of an SD Card (like the ST Disco IOT01A board) the format function does not work. Not sure why. 

A work around I found is to add the following code to the top of main()

```C
    printf("Checking SDCard is Formatted\r\n");
    int err = fs.mount(&sd);
    printf("%s\n", (err ? "Fail :(" : "OK"));
    if (err) {
        // Reformat if we can't mount the filesystem
        // this should only happen on the first boot
        printf("No filesystem found, formatting... ");
        fflush(stdout);
        err = fs.reformat(&sd);
        printf("%s\n", (err ? "Fail :(" : "OK"));
        if (err) {
            error("error: %s (%d)\n", strerror(-err), err);
        }
    }
    // err = fs.unmount();
    // printf("%s\n", (err < 0 ? "Fail :(" : "OK"));
    // if (err < 0) {
    //     error("error: %s (%d)\n", strerror(-err), err);
    // }
```

Example code can be found here: https://github.com/BlackstoneEngineering/mbed-cloud-workshop-connect/#310576453999a900ba059feb3b7c8385aa269956 

## Solution 
Unsure. Dont have time to debug this right now. 

##Tag
@MarceloSalazar

**Comment by MarceloSalazar** [comment]
Hi @BlackstoneEngineering , I've managed to reproduce the problem and have some thoughts on how to proceed.

In the application, you have defined:

`LittleFileSystem fs("sd");` -->  https://github.com/BlackstoneEngineering/mbed-cloud-workshop-connect/blob/master/main.cpp#L54

And then for some reason, the storage doesn't get initialized, and this message is shown:

```
Connecting to the network using Wifi...
Connected to the network successfully. IP address: 192.168.43.17
mbed assertation failed: block < lfs->cfg->block_count, file: ./mbed-os/features/filesystem/littlefs/littlefs/lfs.c, line 27 
```

This fails as soon as `SimpleMbedCloudClient` is initialized here:
https://github.com/ARMmbed/simple-mbed-cloud-client/blob/master/simple-mbed-cloud-client.cpp#L50
And we don't have the chance to check whether the filesystem was mounted or not, and reformat if required.
Maybe this is something that @janjongboom @bridadan could help us to understand?

Alternatively, this works:

`LittleFileSystem fs("sd", &sd);` 

If fails to format, you could enable this option: `MBED_CONF_APP_FORMAT_STORAGE_LAYER_ON_ERROR` to run this [code](https://github.com/ARMmbed/simple-mbed-cloud-client/blob/master/simple-mbed-cloud-client.cpp#L95).
For example in `mbed_app.json`, although I'm keen on leaving the option enabled by default.

Anyway, I'd like to ensure SMCC always works with any supported storage in Mbed OS, regardless on whether the developer writes `fs("sd", &sd)` or `fs("sd")`

Thoughts?

**Comment by MarceloSalazar** [comment]
@geky any thoughts on this?
We're using Mbed OS 5.10 and still seeing this problem.

**Comment by BlackstoneEngineering** [comment]
or, just add the fix i made in my main code to smcc's initializer and call it a day. 

```cpp
int err = fs.mount(&sd);
    printf("%s\n", (err ? "Fail :(" : "OK"));
    if (err) {
        // Reformat if we can't mount the filesystem
        // this should only happen on the first boot
        printf("No filesystem found, formatting... ");
        fflush(stdout);
        err = fs.reformat(&sd);
        printf("%s\n", (err ? "Fail :(" : "OK"));
        if (err) {
            error("error: %s (%d)\n", strerror(-err), err);
        }
    }
```

**Comment by screamerbg** [comment]
@BlackstoneEngineering Can you update this issue based on the latest SMCC release?

**Comment by screamerbg** [comment]
Also note that we've added detection to storage mount to force format the storage - https://github.com/ARMmbed/pelion-ready-example/blob/master/main.cpp#L110
