### ISSUE TITLE
5.10 compatibility (default storage)

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/simple-mbed-cloud-client#18]
Mbed OS 5.10 default storage compatibility needed, FAT is for example hard-coded now.
https://github.com/ARMmbed/simple-mbed-cloud-client/tree/dev#testing

**Comment by MarceloSalazar** [comment]
Thanks for raising this.
I agree we need to update the test config, but also the template app (main.cpp) to use the default storage.

**Comment by MarceloSalazar** [comment]
Fixed in https://github.com/ARMmbed/simple-mbed-cloud-client/pull/19
