### ISSUE TITLE
Convergence with mbed-cloud-client-example...

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/simple-mbed-cloud-client#20]
Now that the Mbed OS 5.10.0 release is coming soon, it brings with it all the default interfaces for block devices and network interfaces. This simplifies quite a bit of the complexity that was originally present in the apis/examples.

What are your thoughts on trying to move the lessons learned with this API back into the mainline `mbed-cloud-client` library and example? It would certainly help remove some of the engineering load and time spent porting this library for each release.

**Comment by MarceloSalazar** [comment]
@bridadan thanks for raising this. @janjongboom and I are definitely interested in this, although need to see some more enhancements. Currently, the `mbed-cloud-client` example is too complex for developers to get started and there are so many unnecessary files (for actual users).
Let's discuss offline.

**Comment by janjongboom** [comment]
@bridadan I've been trying to get simple client mainlined for the last 2.5 years but core team has not taken interest in it.

**Comment by bridadan** [comment]
I'm not sure if we need to get the whole thing mainlined, more like get the key points mainlined. We can't change the whole API at this point. But I think it'd be worth looking into the changes to the client that went in for 5.10 and see how the stack up against what is present here. I wonder if some of the pain points surrounding adding a NetworkInterface and FileSystem have improved.
