### ISSUE TITLE
Add option for the developer to disable all non-critical functions during FW Update

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/simple-mbed-cloud-client#39]
As a developer, I should have an easy way to shut down all but critical functions while downloading a firmware update.

In many cases, running anything during the FW download could potentially cause the download to fail which would leave the device with a firmware image that it cannot verify the integrity of.

**Comment by BlackstoneEngineering** [comment]
This is already possible, add some way to turn off what you're doing (put em in a thread or something), then override this (https://github.com/ARMmbed/simple-mbed-cloud-client/blob/master/update-helper/update-helper.cpp#L75 )  function in your main.cpp and have it terminate the thread. problem solved.

**Comment by screamerbg** [comment]
In fact, the update test is making use of the update helper routines.
