### ISSUE TITLE
Should have typed resources

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/simple-mbed-cloud-client#4]
Right now everything is a string, so you're constantly casting values. This is very error-prone, plus removes all benefits from a statically typed language. MbedCloudClientResource should have type information, either through generics `MbedCloudClientResource<int>` or by specifying particular types like `MbedCloudClientResourceInt`.

I think we could start with just `string`, `int` and `float` and perhaps change at a later point.

**Comment by MarceloSalazar** [comment]
is this still valid or could be closed?

**Comment by janjongboom** [comment]
@MarceloSalazar Still valid.
