### ISSUE TITLE
Include default configuration from mbed_cloud_client_user_config.h

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/simple-mbed-cloud-client#47]
Has been reported by @andrewc-arm 
The configuration file `mbed_cloud_client_user_config.h` is not available in simple-mbed-cloud-client, and hence requires extra step to copy from somewhere else.

We should include a default configuration and have the ability to override from mbed_app.json

**Comment by janjongboom** [comment]
@screamerbg, @MarceloSalazar Because this is very application specific I added it to -example, not to simple-mbed-cloud-client. If you want to override it, fine, but I think it should not live in this repo.

**Comment by screamerbg** [comment]
This is now addressed.
