### ISSUE TITLE
How to unregister a device with SMCC?

### ISSUE THREAD

**Issue by screamerbg** [ARMmbed/simple-mbed-cloud-client#56]
@janjongboom @MarceloSalazar

**Comment by janjongboom** [comment]
You don't at this point. Why do you need this? In my opinion this should not even be a feature.

**Comment by MarceloSalazar** [comment]
Discussed here: https://github.com/ARMmbed/simple-mbed-cloud-client/issues/38

Suggested by @dhwalters423 

"As far as I can tell, there is no API call to deregister a device. The only way you can deregister a device is for the registration timeout to lapse.

We could test this by setting the registration timeout to something very low (like a few seconds)."*
