### ISSUE TITLE
Should be possible to override platform configuration

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/simple-mbed-cloud-client#7]
In this 'simple-mbed-cloud-client' library, there are a few files that are imported by everyone that wants to use the library, regardless on their platform. These define platform configuration.

- `pal_plat_rot_insecure.cpp` --> implementation of the RoT for the platform. By default is fake RoT.

- `sotp_fs_config_MbedOS.h` --> definition of what SOTP / RoT is being used.

- `mbed_cloud_client_user_config_template.h` --> Possible application configuration (TCP, UDP, lifetimes, payload, etc). By default everything is commented out. 

It's ok to define a default implementation or behavior. However, it should be possible to override these functions in the application. One solution is to define those functions as `weak` or use `#ifndef`.

Additionally, these configurations should be documented in the markdown to make application developers aware of this.

FYI @janjongboom

**Comment by screamerbg** [comment]
It's now possible in the latest release. See `mbed_lib.json`
