### ISSUE TITLE
Feature request: include hw/os version as LWM2M resource

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/simple-mbed-cloud-client#83]
Having this information as LWM2M resource would let us monitor device and generate statistics.

FYI @janjongboom @screamerbg

**Comment by janjongboom** [comment]
You can get the target name through `GET_TARGET_NAME(TARGET_NAME)`.

**Comment by screamerbg** [comment]
@janjongboom It seems that there are standard LWM2M resources that aren't populated by default. Is this somethin SMCC can populate during init?
