### ISSUE TITLE
SPDMC tests prints API key

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/simple-mbed-cloud-client#89]
https://github.com/ARMmbed/simple-mbed-cloud-client/blob/v3.0.0.0/TESTS/host_tests/sdk_host_tests.py#L325

Associated security requirement:
`REQ.LG.4: Logs must not contain confidential data.`

**Comment by korjaa** [comment]
Proposed fix: https://github.com/ARMmbed/simple-mbed-cloud-client/pull/90

**Comment by MarceloSalazar** [comment]
PR merged
