### ISSUE TITLE
simple mbed client was disconnecting,  if resource payload size greater than 512 bytes

### ISSUE THREAD

**Issue by thota4u** [ARMmbed/simple-mbed-cloud-client#92]
Hi Team,

We are working on DISCO-L475VG-IOT01A board with WiFi module Inventek ISM43362-M3G-L44 (802.11 b/g/n compliant) for ARM mbed pelion cloud.

issue : simple mbed client was disconnecting,  if resource payload size greater than 512 bytes

[SMCC] Error occurred : MbedCloudClient::ConnectSecureConnectionFailed
[SMCC] Error code : 11
[SMCC] Error details : Client in reconnection mode SecureConnectionFailed

[SMCC] Error occurred : MbedCloudClient::ConnectSecureConnectionFailed
[SMCC] Error code : 11
[SMCC] Error details : Client in reconnection mode SecureConnectionFailed

could you please let me know what may be issue and is there any mbed paramter need to change?.

Thanks &Regards
Praveen.Thota

**Comment by jeromecoutant** [comment]
Hi

Could it be related to https://github.com/ARMmbed/wifi-ism43362/issues/42 ?

Do you use wifi-ism43362 in the master branch ?
