### ISSUE TITLE
How to connect to Leshan server

### ISSUE THREAD

**Issue by wajahat-ublox** [ARMmbed/simple-mbed-cloud-client#98]
Normally we use SMCC to connect to Pelion Device Management however i would like to know if it is possible to use SMCC to connect to Eclipse Leshan server? What changes are required and where?

**Comment by wajahat-ublox** [comment]
@MarceloSalazar

**Comment by MarceloSalazar** [comment]
It should be possible but we haven't tested and can't officially support it.

**Comment by loverdeg-ep** [comment]
I tested this over a year ago with "Mbed client" and the public Leshan server and it worked.
Sorry I don't have any further info.
