### ISSUE TITLE
Archived

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/simple-mbed-cloud-client#99]
🎉🎉🎉🎉

Can it be archived too for good measure?

**Comment by MarceloSalazar** [comment]
@loverdeg-ep we expect this repository to continue to be available at least for a year ;-)

**Comment by 0Grit** [comment]
Available or partially maintained?
Archived doesn't prevent cloning. Just prevents new issues, commits, etc. from being posted.

**Comment by MarceloSalazar** [comment]
Available but not maintained. Anyone can still fork it if they want.
